### ISSUE TITLE
Template strings and JSX embedded 

### ISSUE THREAD

**Issue by sfrench87** [cocopon/vscode-iceberg-theme#2]
![1](https://user-images.githubusercontent.com/48254143/60523776-4293c300-9ce3-11e9-8e31-662f805bbc42.jpg)
![2](https://user-images.githubusercontent.com/48254143/60523777-432c5980-9ce3-11e9-856a-d4a0bdceeca5.jpg)

The color of the code inside the braces changes and the JSX braces change between white and purple.

**Comment by cocopon** [comment]
Thank you for reporting, could you share a minimal code and its language mode to reproduce the issue?

**Comment by sfrench87** [comment]
Here is a quick sample, you will need the [styled components](https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components) extensions for that to be colored.

https://gist.github.com/sfrench87/a565ff97f57192ce36984b919a229859

**Comment by cocopon** [comment]
Above-mentioned gist seems to be 404. Feel free to reopen the issue if you still have a problem.
