### ISSUE TITLE
Menubar color doesn't match with rest of the interface

### ISSUE THREAD

**Issue by mittalyashu** [cocopon/vscode-iceberg-theme#4]
![image](https://user-images.githubusercontent.com/29014463/61199587-21c46800-a6fc-11e9-9a08-8f0269671858.png)

The color of menubar doesn't match the rest of the interface.

How about, something like this?

![image](https://user-images.githubusercontent.com/29014463/61199885-381ef380-a6fd-11e9-88e9-f1a0d6e437b0.png)

**Comment by cocopon** [comment]
I agree with you. Checked the title bar on Windows and updated title, bottom, and menu colors. I'll publish them later.

![image_preview](https://user-images.githubusercontent.com/602961/61760954-27126880-ae08-11e9-8c07-1261b6abb845.png)
![image_preview (1)](https://user-images.githubusercontent.com/602961/61760955-28439580-ae08-11e9-8a5e-c63afa6d07f4.png)

**Comment by cocopon** [comment]
Released in [0.0.7](https://github.com/cocopon/vscode-iceberg-theme/releases/tag/0.0.7). Thank you for reporting the issue.
