### ISSUE TITLE
Different gutter color

### ISSUE THREAD

**Issue by madprops** [cocopon/vscode-iceberg-theme#5]
Hi, thanks for this nice theme. I know this is personal opinion, but I instantly found the default gutter color too in-your-face, too much contrast. Just some feedback. 

This is how it looks when I set it to the same color as the code area:

![Screenshot_20200722_220841](https://user-images.githubusercontent.com/206498/88251471-21906e00-cc68-11ea-9e27-435c95d78e76.jpg)

**Comment by cocopon** [comment]
It looks cool and clean but hard to see indents.

**Comment by cocopon** [comment]
Feel free to reopen the issue if you still have a problem.
