### ISSUE TITLE
Bad contrast in search

### ISSUE THREAD

**Issue by madprops** [cocopon/vscode-iceberg-theme#6]
![Screenshot_20200722_221131](https://user-images.githubusercontent.com/206498/88251538-556b9380-cc68-11ea-9153-7d87d60479eb.jpg)

As you can see the orange makes it hard to read. This probably also applies to other parts of the interface but I noticed it in the ctrl+shift+f search panel

**Comment by gkeep** [comment]
Yeah, I think an overhaul is long overdue. Might pick this up and see how it goes. ¯\\_(ツ)_/¯
